---

- name: "Initialize mailhog_docker_ports fact"
  set_fact:
    mailhog_docker_ports:
      - "{{ mailhog_api_bind_port }}:{{ mailhog_api_bind_port }}/tcp"
      - "{{ mailhog_ui_bind_port }}:{{ mailhog_ui_bind_port }}/tcp"
      - "{{ mailhog_smtp_bind_port }}:{{ mailhog_smtp_bind_port }}/tcp"

- name: "[docker] Setup the mailhog docker container"
  docker_container:
    name: mailhog
    image: mailhog/mailhog:latest
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: "{{ mailhog_docker_ports | unique }}"
    env:
      MH_HOSTNAME: "{{ mailhog_hostname }}"
      MH_API_BIND_ADDR: "{{ mailhog_api_bind_addr }}:{{ mailhog_api_bind_port }}"
      MH_UI_BIND_ADDR: "{{ mailhog_ui_bind_addr }}:{{ mailhog_ui_bind_port }}"
      MH_SMTP_BIND_ADDR: "{{ mailhog_smtp_bind_addr }}:{{ mailhog_smtp_bind_port }}"
      MH_STORAGE: "{{ mailhog_storage }}"
      MH_MONGO_COLLECTION: "{{ mailhog_mongodb_collection }}"
      MH_MONGO_DB: "{{ mailhog_mongodb_db }}"
      MH_MONGO_URI: "{{ mailhog_mongodb_uri }}"
